version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: obras_dashboard
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=obras_dashboard
      - DB_PORT=5432
      - PORT=3000
    depends_on:
      - db
    volumes:
      - ./:/app/frontend

volumes:
  pgdata:
